% Eli Bowen
% 2/27/2020
% wrapper around the rastamat library MFCC functionality (https://labrosa.ee.columbia.edu/matlab/rastamat/)
% USAGE:
%   [data,Fs] = audioread(fullfile('D:', 'datasets/audio/Harry_Potter_and_the_Chamber_of_Secrets-English/001_harry_potter_and_the_chamber_of_secrets_US_ch_001_the_worst_birthday-96k.wav'));
%   data = MFCC(data, Fs, 2*128, 128);
% INPUT:
%	data - PCM audio vector
%	Fs - sampling rate of the audio
%	windowSz - size of temporal window in units of number of SAMPLES (not ms)
%	stepSz - size of temporal step in units of number of SAMPLES (not ms)
% RETURNS:
%   data - nSteps x 60 double
function [data] = MFCC (data, Fs, windowSz, stepSz)
    validateattributes(data, {'numeric'}, {'nonempty','vector'});
    validateattributes(Fs, {'numeric'}, {'nonempty','scalar','positive','integer'});
    validateattributes(windowSz, {'numeric'}, {'nonempty','scalar','positive','integer'});
    validateattributes(stepSz, {'numeric'}, {'nonempty','scalar','positive','integer'});

    % convert to MFCCs very close to those generated by feacalc -sr 22050 -nyq 8000 -dith -hpf -opf htk -delta 0 -plp no -dom cep -com yes -frq mel -filt tri -win 32 -step 16 -cep 20
    data = data .* 3.3752;
    data = melfcc(data, Fs, 'maxfreq', 8000, 'numcep', 20, 'nbands', 22, 'fbtype', 'fcmel', 'dcttype', 1, 'usecmp', 1, 'wintime', windowSz/Fs, 'hoptime', stepSz/Fs, 'preemph', 0, 'dither', 1);
    del = deltas(data);
    ddel = deltas(deltas(data, 5), 5); % double deltas are deltas applied twice with a shorter window
    data = [data;del;ddel]; % composite, 60-element feature vector
    data = data';
end