% Eli Bowen
% 10/1/2021
% wrapper designed to simplify and remove the chance of errors when calling liblinear's predict() function
% designed to work with liblinear-multicore version 2.43-2
% INPUTS:
%   model - struct generated by TrainLiblinear()
%   label - 1 x n_datapts (numeric)
%   data - n_datapts x ? (numeric or logical)
% RETURNS:
%   predLabel - 1 x n_datapts
%   acc - scalar (numeric) - accuracy ranged 0 --> 1
%   score - 1 x n_datapts
%   mse - scalar (numeric) - mean squared error
%   sqcorr - scalar (numeric) - squared correlation coefficient
function [predLabel,acc,score,mse,sqcorr] = LiblinearPredict (model, label, data)
    validateattributes(model, {'struct'}, {'nonempty','scalar'});
    validateattributes(label, {'numeric'}, {'nonempty','vector','positive','integer'});
    validateattributes(data, {'double','logical'}, {'nonempty','2d','nonnan','nrows',numel(label)});
    if islogical(data)
        data = double(data);
    end

    [predLabel,temp,score] = predict(label, sparse(data), model, '-q'); % temp = [accuracy out of 100, MSE, squared correlation coeff]
    acc    = temp(1) / 100; % convert to range 0-->1 to be more like most matlab accuracy measures
    mse    = temp(2);
    sqcorr = temp(3);
end