% Eli Bowen
% 5/1/2021
% we're using "cube coordinates" from www.redblobgames.com/grids/hexagons and the "pointy" hexagon configuration, but modified to map to our hex grid generated by SpreadItemsOn2DHexGrid...()
% INPUTS:
%   pt - n_points x 2 (numeric)
%   scaleFactor - scalar (numeric)
% RETURNS:
%   pt - n_points x 3 (numeric)
function [pt] = Pixel2Hex(pt, scaleFactor)
    validateattributes(pt, 'numeric', {'nonempty','2d','ncols',2});
    validateattributes(scaleFactor, 'numeric', {'nonempty','scalar'});

    pt = pt ./ scaleFactor;

    q = fix(pt(:,1) - pt(:,2) ./ (sqrt(3)));
    r = fix(pt(:,2) ./ (sqrt(3)/2));
%     q = sqrt(3) .* (1/3) .* pt(:,1) - (1/3) .* pt(:,2);
%     r = (2/3) ./ (sqrt(3)/2) .* pt(:,2);

    % convert axial coordinates to cube coordinates
    x = q;
    z = r;
    y = -x - z;
    pt = [x(:),y(:),z(:)];

    assert(sum(pt(:)) == 0); % valid cubic hex coordinates sum to 0 (else we have >1 cubic coord matching same 2D coord)

    % now consider rounding via hex_round()
end